compiler/c/cfc.c
compiler/go/cfc/cfc.go
compiler/src/CFCBindClass.c
compiler/src/CFCBindCore.c
compiler/src/CFCC.c
compiler/src/CFCC.h
compiler/src/CFCPerl.c
compiler/src/CFCPerlMethod.c
runtime/go/build.go

Refactor CFC internals to eliminate an autogenerated file and centralize some code generation rather than perform generation per-host.
This fixes CLOWNFISH-30.

CLOWNFISH-30 Kill callbacks.h

---

compiler/src/CFCFunction.c
compiler/src/CFCFunction.h
compiler/src/CFCMethod.c
compiler/src/CFCMethod.h
compiler/src/CFCPerlClass.c
compiler/src/CFCPerlMethod.c
compiler/src/CFCPerlMethod.h
compiler/src/CFCPerlSub.c
compiler/src/CFCPerlSub.h

Consolidate tests for whether Clownfish functions and methods can be bound to a host.

CLOWNFISH-32 can_be_bound

---

compiler/perl/lib/Clownfish/CFC.pm
compiler/perl/lib/Clownfish/CFC.xs
compiler/src/CFCClass.c
compiler/src/CFCClass.h
compiler/src/CFCParseHeader.y
compiler/src/CFCTestClass.c
compiler/src/CFCTestDocuComment.c
compiler/src/CFCTestType.c
runtime/core/Clownfish/Obj.cfh

The keyword "abstract" is only advisory when applied to classes.  It would be nice if the compiler at least captured it, even if it doesn't yet do anything with it.
See CLOWNFISH-32.

CLOWNFISH-32 capture "abstract" keyword

---

compiler/src/CFCBindClass.c
compiler/src/CFCPerl.c
runtime/core/Clownfish/Blob.c
runtime/core/Clownfish/ByteBuf.c
runtime/core/Clownfish/CharBuf.c
runtime/core/Clownfish/Err.c
runtime/core/Clownfish/Err.cfh
runtime/core/Clownfish/Hash.c
runtime/core/Clownfish/Num.c
runtime/core/Clownfish/Obj.c
runtime/core/Clownfish/Obj.cfh
runtime/core/Clownfish/String.c
runtime/core/Clownfish/Test/TestObj.c
runtime/core/Clownfish/TestHarness/TestFormatter.c
runtime/core/Clownfish/TestHarness/TestSuite.c
runtime/core/Clownfish/Vector.c
runtime/go/clownfish/clownfish.go
runtime/perl/buildlib/Clownfish/Build/Binding.pm
runtime/perl/t/binding/019-obj.t
runtime/perl/xs/XSBind.c
runtime/ruby/ext/Bind.c

Second version of the pull request that adds type-safe wrappers for `get_class`, `get_class_name`, and `is_a` for each class. I chose lowercase names like `Str_is_a` because I find them easier to read and write. I'm aware that this could result in a name clash if someone decides to implement an inert function like `is_a` in a class. But this would be a really bad idea anyway, so I don't think it's a problem.

CLOWNFISH-50-obj-method-to-inert-v2

---

compiler/src/CFCBindClass.c
compiler/src/CFCBindCore.c
compiler/src/CFCGoFunc.c
compiler/src/CFCGoFunc.h
compiler/src/CFCGoMethod.c
compiler/src/CFCGoTypeMap.c
compiler/src/CFCParcel.c
compiler/src/CFCParcel.h
compiler/src/CFCType.c
runtime/go/build.go
runtime/go/clownfish/clownfish.go
runtime/go/clownfish/string_test.go

Clownfish methods which are bound to Go should accept Go strings as arguments and return Go strings, rather than requiring the user to convert string types.
Go's memory model doesn't allow for sharing string data, so we can't use stack-allocated string wrappers as we have in the Perl bindings and each conversion will involve allocating a full new copy. At least the copies are guaranteed to be cleaned up by the Go garbage collector, though.

CLOWNFISH-51 Go string conversion

---

compiler/src/CFCGo.c
compiler/src/CFCGoClass.c
compiler/src/CFCGoClass.h
compiler/src/CFCGoFunc.c
compiler/src/CFCGoFunc.h
compiler/src/CFCGoMethod.c
compiler/src/CFCGoTypeMap.c
runtime/go/clownfish/clownfish.go

Autogenerate Go constructor bindings.
The constructors follow Go naming conventions, following the proof-of-concept bindings: `NewFoo()`
Subtyping is not supported. Under the hood, we use the inert function `new` when available -- unlike the Perl bindings, which use `init`.
This "v2" pull request differs from the original in that it has been rebased on top of current master and it omits the ill-considered requirement that a constructor function be public for the autogenerated binding to trigger.  It also drops the commit making Err's constructor public.

CLOWNFISH-32 Go constructor autogen v2

---

compiler/perl/lib/Clownfish/CFC.pm
compiler/perl/lib/Clownfish/CFC.xs
compiler/perl/t/100-type.t
compiler/perl/t/105-object_type.t
compiler/src/CFCGoFunc.c
compiler/src/CFCGoTypeMap.c
compiler/src/CFCTestType.c
compiler/src/CFCType.c
compiler/src/CFCType.h

Autogenerated bindings for Clownfish subroutines which accept or return
clownfish Obj should be mapped to Go's "empty interface" type, `interface{}`.
This sacrifices some type safety, but it is the only way to achieve certain
desirable effects.  For example, it should be possible for Vector's Push()
method to take a Go string, instead of requiring the user to perform a manual
conversion to a Clownfish object.  Similarly, Vector's Pop() should be able to
return a Go string.
Functions which need to return an actual clownfish Obj wrapped in a Go struct
will need to have hand-coded bindings, but there are fewer of those so
converting Obj by default is the better choice.

CLOWNFISH-57 Obj to Go empty interface

---

runtime/core/Clownfish/Hash.cfh
runtime/core/Clownfish/Test/TestHash.c
runtime/perl/buildlib/Clownfish/Build/Binding.pm
runtime/perl/t/binding/017-hash.t

The signature for Hash's Store() method should accept `nullable` values.  The implementation is already safe for use with NULL values, and we had already discussed that we needed `Has_Key` to identify keys mapped to NULL.

CLOWNFISH-58 Hash Store nullable

---

runtime/go/build.go
runtime/go/clownfish/blob_test.go
runtime/go/clownfish/boolean_test.go
runtime/go/clownfish/clownfish.go
runtime/go/clownfish/err_test.go
runtime/go/clownfish/float_test.go
runtime/go/clownfish/hash_test.go
runtime/go/clownfish/integer_test.go
runtime/go/clownfish/string_test.go
runtime/go/clownfish/vector_test.go

Refine the Go bindings and improve testing for Vector, Hash, Blob, Integer, Float, Boolean, String, and Err.

CLOWNFISH-59 Refine Go core types

---

runtime/core/Clownfish/ByteBuf.c
runtime/core/Clownfish/ByteBuf.cfh
runtime/core/Clownfish/Test/TestByteBuf.c
runtime/go/build.go
runtime/go/clownfish/bytebuf_test.go
runtime/go/clownfish/charbuf_test.go
runtime/go/clownfish/class_test.go
runtime/go/clownfish/clownfish.go
runtime/go/clownfish/hash_test.go
runtime/go/clownfish/method_test.go
runtime/go/clownfish/string_test.go
runtime/go/ext/clownfish.c

Refine the Go bindings for Class, Method, CharBuf, ByteBuf and StringIterator and add tests.
This branch also changes ByteBuf's `Cat()` to take a Blob rather than another ByteBuf, similar to how CharBuf's `Cat()` takes a String.
Compared to v1, this pull request...
* Customizes the Go binding for `Class_Make_Obj`.
* Adds testing for the Hash Go bindings for storing nil values.
* Fixes a bad assignment in the ByteBuf tests.

Clownfish 59 refine go other types v2

---

runtime/go/build.go
runtime/go/clownfish/clownfish.go
runtime/go/clownfish/test.go
runtime/go/clownfish/test_test.go
runtime/go/ext/testclownfish.c

Run the core tests under the Go bindings.
Some kludges are necessary to suppress failures in Err, whose usage of thread-local storage is not compatible with Go's concurrency model.

CLOWNFISH-61 Run core tests under Go

---

compiler/src/CFCGoFunc.c
compiler/src/CFCGoFunc.h
compiler/src/CFCGoMethod.c
runtime/core/Clownfish/TestHarness/TestSuite.cfh
runtime/go/clownfish/bytebuf_test.go
runtime/go/clownfish/charbuf_test.go
runtime/go/clownfish/class_test.go
runtime/go/clownfish/hash_test.go
runtime/go/clownfish/method_test.go
runtime/go/clownfish/string_test.go
runtime/go/clownfish/vector_test.go

Clownfish methods which are not marked as `public` should have the first letter of their Go method name downcased so that they are not exported by the Go package.
This pull requests differs from v1 in that it adds a missing include for ctype.h which caused an Appveyor CI failure.

CLOWNFISH-63 Don't export private methods via Go v2

---

compiler/src/CFCPerlPod.c
runtime/core/Clownfish/Class.cfh

Now the generated POD looks like
=head2 glean_query
$searcher->glean_query($query);
$searcher->glean_query();  # default: undef
[...]
=head2 hits
$searcher->hits(
query      => $obj,        # required
offset     => $int,        # default: 0
num_wanted => $int,        # default: 10
sort_spec  => $sort_spec,  # default: undef
);
[...]
This also makes it possible to link to the POD section of a method or constructor.
Having `$int` appear multiple times in the example above might be confusing. Maybe the following more verbose format is better?
$searcher->hits(
query      => $query,       # Clownfish::Obj, required
offset     => $offset,      # integer, default: 0
num_wanted => $num_wanted,  # integer, default: 10
sort_spec  => $sort_spec,   # Lucy::Search::SortSpec, default: undef
);
Other …

CLOWNFISH-64 Autogenerate Perl subroutine code samples

---

runtime/core/Clownfish/Boolean.c
runtime/core/Clownfish/Boolean.cfh
runtime/core/Clownfish/Num.c
runtime/core/Clownfish/Num.cfh
runtime/core/Clownfish/Test/TestBoolean.c
runtime/go/clownfish/boolean_test.go
runtime/go/clownfish/float_test.go
runtime/go/clownfish/integer_test.go
runtime/perl/t/binding/031-num.t

These methods used to be "virtual" methods defined in `Obj`. Now that they're non-virtual, there's no real use for them. Simply call `Get_Value` and convert the value manually.

Remove Bool to Num conversion methods

---

compiler/python/clownfish/_cfc.c
compiler/python/clownfish/cfc/__init__.py
compiler/python/setup.py
compiler/python/test/test_cfc.py

Improve basic CFC Python bindings.
*   Migrate to Charmonizer-generated Makefile build.
*   Add a "test" target to setup.py.
*   Add bindings for a few more parts of the CFC core.

CLOWNFISH-66 Python CFC core

---

compiler/include/CFC.h
compiler/src/CFCPyClass.c
compiler/src/CFCPyClass.h
compiler/src/CFCPython.c
runtime/core/Clownfish/Class.c
runtime/core/Clownfish/Class.cfh
runtime/core/Clownfish/Method.c
runtime/core/Clownfish/Method.cfh
runtime/perl/xs/XSBind.c
runtime/python/cfext/CFBind.c
runtime/python/cfext/CFBind.h
runtime/python/test/test_clownfish.py

Make PyTypeObjects and Clownfish Classes work together.
* Generate PyTypeObject def for each Clownfish class.
* Object allocation and initialization for Py glue.
* Make Clownfish classes aware of their corresponding PyTypeObjects.
* Bootstrap Clownfish parcels and Classes, Python type objects and modules.

CLOWNFISH-66 Py glue part 2

---

compiler/src/CFCPyClass.c
compiler/src/CFCPyMethod.c
compiler/src/CFCPyMethod.h
runtime/python/cfext/CFBind.c
runtime/python/test/test_clownfish.py
runtime/python/test/test_err.py
runtime/python/test/test_hash.py

Gen Py glue for methods and constructors.
* Autogenerate CPython glue code for methods and constructors.
* Handle both positional and labeled args.
* Deal with refcounting of args and return values.
* Trap Clownfish exceptions and rethrow as Python exceptions.
* Unit test Py binding of Hash.

CLOWNFISH-66 Py glue part 3

---

runtime/core/Clownfish/String.c

Inside Str_To_F64 we use strtod, which requires a nul-terminated C
string argument.  Now that Clownfish Strings consistently lack
nul-termination, we need to copy content into a nul-terminated buffer
and pass that to strtod.

CLOWNFISH-84 guarantee null-terminated arg to strtod

---

compiler/perl/lib/Clownfish/CFC/Perl/Build.pm
compiler/perl/lib/Clownfish/CFC/Perl/Build/Charmonic.pm
runtime/common/charmonizer.c
runtime/common/charmonizer.main
runtime/perl/.gitignore
runtime/perl/buildlib/Clownfish/Build.pm

Let Charmonizer create a Makefile for the Perl bindings that builds the
core object files. The list of object files is passed in a Charmonizer
variable named `CORE_OBJECTS`.
Make options can be passed by running
perl Build.PL --charmonizer_params make_options=<options>
Module::Build options can also be specified in ~/.modulebuildrc, so an
easy way to always launch parallel builds is to add a line like
Build_PL --charmonizer_params make_options=-j5

Perl build with make

---

compiler/c/.gitignore
compiler/common/charmonizer.c
compiler/common/charmonizer.main
compiler/src/CFCPerl.c
runtime/c/src/tls.c
runtime/common/charmonizer.c
runtime/common/charmonizer.main
runtime/perl/xs/XSBind.c

Rework the Charmonizer fragments to use the new API to build binaries.
Build a static library from the core source files of the CFC C build
which is used for both the main and test executable. Remove some
unnecessary stuff from the Makefiles for other host languages.

Switch to new Charmonizer Make API
